### ISSUE TITLE
APIEnumNotUpToDateException

### ISSUE THREAD

**Issue by IKERNEII** [stelar7/L4J8#3]
Hey there,
I've tried to access the match history of users and cam across a problem. When i call the method wich uses matchAPI.getMatchList this error is thrown:
`Caused by: no.stelar7.api.l4j8.basic.exceptions.APIEnumNotUpToDateException: The enum no.stelar7.api.l4j8.basic.constants.types.LaneType is missing the type "NONE"!
Please make sure you have the latest version of the library!
If you do, send this message to the maintainer of the API.
	at no.stelar7.api.l4j8.basic.deserializer.LaneTypeDeserializer.lambda$deserialize$0(LaneTypeDeserializer.java:16)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at no.stelar7.api.l4j8.basic.deserializer.LaneTypeDeserializer.deserialize(LaneTypeDeserializer.java:16)
	at no.stelar7.api.l4j8.basic.deserializer.LaneTypeDeserializer.deserialize(LaneTypeDeserializer.java:9)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at no.stelar7.api.l4j8.basic.calling.DataCallBuilder.build(DataCallBuilder.java:76)
	at no.stelar7.api.l4j8.impl.raw.MatchAPI.getMatchList(MatchAPI.java:105)
	at de.gaming_ww.discordbot.core.LeagueOfLegends.RiotApiRequests.getRecentPre`

I wanted to ask if this is an issue from my side or if it's an issue with the wrapper and how this could be avoided.

**Comment by stelar7** [comment]
That should have been fixed with a7fa10141f, so if youre using the latest version that shouldnt happen
