### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ChristianKern97** [stelar7/L4J8#5]
I don't really know if this is an issue with the wrapper or with my code but i'm at a loss...
So i try to receive the matchlist of a accountId 
`l4j8.getMatchAPI().getMatchList(region,accountId,null,null,null,null,queueTypes,null,null);`

but this allways returns some AccessDenied Error
`<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>A28BD5597C8B5D54</RequestId><HostId>m2IvLEnE2o0m4pBUccc8iK9KJ/BSa5NA12vO691BLzFZKQ9CGsvUrcI1CNnmd1rc2bBQS6ippTY=</HostId></Error>`

if i try my api key and the accountId with the pure link it works. If you got an idea where this is coming from let me know.

**Comment by ChristianKern97** [comment]
The odd thing is the same code works just fine in other projects...

The line where the error occurs is the case 403 in DataCallBuilder but with the odd responseData

The entire error is:
```
Exception in thread "main" no.stelar7.api.l4j8.basic.exceptions.APIResponseException: The API denied your request!
Your API key might be invalid
You may be trying to call a endpoint you dont have access to
or if you just regenerated it; wait a few seconds, then try again
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>3A4EE40855A16893</RequestId><HostId>jGVmiuWohnyxTMKUtfgXoFhkczK0osH3epw66kDeVU1ktImfUhScOnpdIQdm+9VCsLk9Kn+HMMA=</HostId></Error>
	at no.stelar7.api.l4j8.basic.calling.DataCallBuilder.build(DataCallBuilder.java:89)
	at no.stelar7.api.l4j8.impl.raw.MatchAPI.getMatchList(MatchAPI.java:105)
	at mining.apis.riotapi.Requests.getListOfRecentGames(Requests.java:22)
```

The code is very straight forward:
```
    public static List<MatchReference> getListOfRecentGames(long accountId) {
        Set<GameQueueType> queueTypes = new HashSet<>();
        queueTypes.add(GameQueueType.RANKED_SOLO_5X5);
        
        return l4j8.getMatchAPI().getMatchList(region, accountId, null, null, null, null, queueTypes, null, null);
    }

    static APICredentials credentials = new APICredentials(apiKey);
    static L4J8 l4j8 = new L4J8(credentials);
    static Platform region = Platform.EUW1;
```

Also this is only one method where the error occures, if i make a okhttp request (which works) other methods also throw this odd error. 
It's so weird that it works in other similar projects. I reimported the whole maven dependency list automatically and manually several times.

I hope you can help but don't worry if you can't :)

**Comment by stelar7** [comment]
I am unable to reproduce your error.. 🤔 

Try adding
`DataCall.setLogLevel(LogLevel.DEBUG);`
at the start of your method, then post that output.
([like this](https://github.com/stelar7/L4J8/blob/8f1cb2e3fefe59e839f8d08a066899cd56c44d3b/src/test/java/no/stelar7/api/l4j8/tests/match/MatchListTest.java#L87-L99))

**Comment by ChristianKern97** [comment]
Cool that's a nice feature. I got a lot of information:
```
DEBUG: RateLimit{permits=20, delayInMs=1000}: current call count: 1
DEBUG: RateLimit{permits=100, delayInMs=120000}: current call count: 6
DEBUG: Loaded ratelimit for V3_MATCHLIST
DEBUG: RateLimit{permits=1000, delayInMs=10000}: current call count: 1
INFO: Trying url: http://ddragon.leagueoflegends.com/lolmatchv3matchlists/by-account/34933969?queue=420
EXTENDED_INFO: URL                 : http://ddragon.leagueoflegends.com/lolmatchv3matchlists/by-account/34933969?queue=420
Request Method      : GET                                     
POST                :                                         
Request Headers     :                                         
	Accept-Charset           : [ISO-8859-1,utf-8]                      
	X-Riot-Token             : [RGAPI-50c90dd7-6841-4e30-a005-07be8acbed49]
	Cache-Control            : [no-store,max-age=0,no-cache]           
	User-Agent               : [L4J8]                                  
	Pragma                   : [no-cache]                              
	Expires                  : [0]                                     
	Accept-Language          : [en-US]                                 
	Content-Type             : [application/json]
EXTENDED_INFO: Response Headers    :                                         
EXTENDED_INFO: 	Transfer-Encoding        : [chunked]                               
EXTENDED_INFO: 	null                     : [HTTP/1.1 403 Forbidden]                
EXTENDED_INFO: 	X-Cache                  : [Error from cloudfront]                 
EXTENDED_INFO: 	Server                   : [AmazonS3]                              
EXTENDED_INFO: 	Access-Control-Allow-Origin: [*]                                     
EXTENDED_INFO: 	Access-Control-Allow-Methods: [GET, HEAD]                             
EXTENDED_INFO: 	Connection               : [keep-alive]                            
EXTENDED_INFO: 	X-Amz-Cf-Id              : [pGpA2Qt8lMk2F_-efsLmV496gOf852ZOlM8lcFGQQesl6Cba3Q_0GA==]
EXTENDED_INFO: 	Access-Control-Max-Age   : [3000]                                  
EXTENDED_INFO: 	Date                     : [Tue, 31 Jul 2018 17:52:43 GMT]         
EXTENDED_INFO: 	Via                      : [1.1 c205f1b841011a5b4b893843ca879e5a.cloudfront.net (CloudFront)]
EXTENDED_INFO: 	Content-Type             : [application/xml]                       
DEBUG: Header 'X-App-Rate-Limit' missing from call: http://ddragon.leagueoflegends.com/lolmatchv3matchlists/by-account/34933969?queue=420
DEBUG: Header 'X-Method-Rate-Limit' missing from call: http://ddragon.leagueoflegends.com/lolmatchv3matchlists/by-account/34933969?queue=420
EXTENDED_INFO: DataCallResponse
{
	responseCode=403
	responseData=
	<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>930356C14B487244</RequestId><HostId>GyLW52x+whUeRPnpkVRZ7GPWpa5Wk84cuvqsSdwl/6jcZIyr2XOGT3nG9N67sRZzWHZR3Yhx0vg=</HostId></Error>

}
Exception in thread "main" no.stelar7.api.l4j8.basic.exceptions.APIResponseException: The API denied your request!
Your API key might be invalid
You may be trying to call a endpoint you dont have access to
or if you just regenerated it; wait a few seconds, then try again
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>930356C14B487244</RequestId><HostId>GyLW52x+whUeRPnpkVRZ7GPWpa5Wk84cuvqsSdwl/6jcZIyr2XOGT3nG9N67sRZzWHZR3Yhx0vg=</HostId></Error>
	at no.stelar7.api.l4j8.basic.calling.DataCallBuilder.build(DataCallBuilder.java:89)
	at no.stelar7.api.l4j8.impl.raw.MatchAPI.getMatchList(MatchAPI.java:105)
	at mining.apis.riotapi.Requests.getListOfRecentGames(Requests.java:24)
	at mining.DataMinerController.getUserGames(DataMinerController.java:53)
	at mining.DataMinerController.addNewGames(DataMinerController.java:47)
	at mining.DataMinerController.run(DataMinerController.java:137)
	at Main.main(Main.java:17)
```
I'm not sure but the URL looks odd to me 😄

**Comment by stelar7** [comment]
oh.. that.. hmm.. Do you use the DDragon api somewhere in your code?

**Comment by ChristianKern97** [comment]
Yap to get the versions. Is that the problem?

**Comment by ChristianKern97** [comment]
Thanks
